web:
  host: 0.0.0.0
  # 网页端口
  port: 80

server:
  # 显示服务器连接信息
  show-info: true
  # 显示服务器端口
  show-port: false
  # 服务器名字
  name: Minecraft Server
  # 服务器地址
  host: localhost
  # 服务器端口
  port: 25565
  # 查询端口
  query: 25565
  # 网站图标
  logo: ./images/logo.png